import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#21005d',
        'inverse-primary': '#dcb8ff',
        'surface': '#faf9fc',
        'on-background': '#1b1b1e',
        'outline': '#7c7481',
        'surface-container-highest': '#e3e2e6',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#001a42',
        'inverse-on-surface': '#f2f0f4',
        'surface-tint': '#7549a4',
        'secondary': '#005ac4',
        'surface-container': '#efedf1',
        'surface-bright': '#faf9fc',
        'surface-dim': '#dbd9dd',
        'tertiary-fixed-dim': '#cebdff',
        'on-tertiary-container': '#fffbff',
        'primary-container': '#8d60bc',
        'background': '#faf9fc',
        'on-tertiary-fixed-variant': '#4e388a',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#e8ddff',
        'error': '#ba1a1a',
        'outline-variant': '#cdc3d2',
        'primary-fixed': '#f0dbff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#303033',
        'on-surface-variant': '#4b4450',
        'on-primary': '#ffffff',
        'on-surface': '#1b1b1e',
        'primary-fixed-dim': '#dcb8ff',
        'surface-container-high': '#e9e7eb',
        'tertiary': '#634ea1',
        'on-primary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#004396',
        'primary': '#7346a1',
        'secondary-fixed': '#d8e2ff',
        'secondary-container': '#5491ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#5c308a',
        'surface-variant': '#e3e2e6',
        'surface-container-low': '#f5f3f7',
        'on-primary-container': '#fffbff',
        'on-error-container': '#93000a',
        'tertiary-container': '#7d67bc',
        'on-secondary-container': '#002a62',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#aec6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config

